# Generated by Django 4.2.1 on 2023-06-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
